CREATE SCHEMA IF NOT EXISTS CRM AUTHORIZATION SA;
CREATE SEQUENCE crm.appinfo_id_seq;

-- 0 +/- SELECT COUNT(*) FROM CRM.APP_USER;
CREATE CACHED TABLE CRM.APPINFO_0(
    ID BIGINT DEFAULT (NEXT VALUE FOR CRM.SYSTEM_SEQUENCE_2FFA3CB0_AC70_4742_9281_0CFFB6B37C2F) NOT NULL NULL_TO_DEFAULT SEQUENCE CRM.SYSTEM_SEQUENCE_2FFA3CB0_AC70_4742_9281_0CFFB6B37C2F,
    APP_NAME VARCHAR(20),
    APP_TYPE SMALLINT NOT NULL,
    LATEST_VERSION VARCHAR(20),
    PATH VARCHAR(100),
    DESCRIPTION VARCHAR(50),
    FORCE_UPGRADE_VERSIONS VARCHAR(200),
    CTIME TIMESTAMP DEFAULT NOW() NOT NULL,
    MTIME TIMESTAMP DEFAULT NOW() NOT NULL
);
ALTER TABLE CRM.APPINFO_0 ADD CONSTRAINT CRM.APPINFO_0_PK_ID PRIMARY KEY(ID);
CREATE CACHED TABLE CRM.APPINFO_1(
    ID BIGINT DEFAULT (NEXT VALUE FOR CRM.SYSTEM_SEQUENCE_2FFA3CB0_AC70_4742_9281_0CFFB6B37C2F) NOT NULL NULL_TO_DEFAULT SEQUENCE CRM.SYSTEM_SEQUENCE_2FFA3CB0_AC70_4742_9281_0CFFB6B37C2F,
    APP_NAME VARCHAR(20),
    APP_TYPE SMALLINT NOT NULL,
    LATEST_VERSION VARCHAR(20),
    PATH VARCHAR(100),
    DESCRIPTION VARCHAR(50),
    FORCE_UPGRADE_VERSIONS VARCHAR(200),
    CTIME TIMESTAMP DEFAULT NOW() NOT NULL,
    MTIME TIMESTAMP DEFAULT NOW() NOT NULL
);
ALTER TABLE CRM.APPINFO_1 ADD CONSTRAINT CRM.APPINFO_1_PK_ID PRIMARY KEY(ID);
CREATE CACHED TABLE CRM.APPINFO_2(
    ID BIGINT DEFAULT (NEXT VALUE FOR CRM.SYSTEM_SEQUENCE_2FFA3CB0_AC70_4742_9281_0CFFB6B37C2F) NOT NULL NULL_TO_DEFAULT SEQUENCE CRM.SYSTEM_SEQUENCE_2FFA3CB0_AC70_4742_9281_0CFFB6B37C2F,
    APP_NAME VARCHAR(20),
    APP_TYPE SMALLINT NOT NULL,
    LATEST_VERSION VARCHAR(20),
    PATH VARCHAR(100),
    DESCRIPTION VARCHAR(50),
    FORCE_UPGRADE_VERSIONS VARCHAR(200),
    CTIME TIMESTAMP DEFAULT NOW() NOT NULL,
    MTIME TIMESTAMP DEFAULT NOW() NOT NULL
);
ALTER TABLE CRM.APPINFO_2 ADD CONSTRAINT CRM.APPINFO_2_PK_ID PRIMARY KEY(ID);
-- 1 +/- SELECT COUNT(*) FROM CRM.APPINFO;
create view crm.appinfo as select * from crm.appinfo_0 union all select * from crm.appinfo_1 union all select * from crm.appinfo_2;

